spring.application.name=TrafficSignDetection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.connection.characterEncoding=utf8mb4
spring.jpa.properties.hibernate.connection.useUnicode=true

server.port=8080

signer_key=${SIGNER_KEY}

logging.level.org.springframework.security=DEBUG

b2.endpoint=${B2_ENDPOINT}
b2.access-key=${B2_ACCESS_KEY}
b2.secret-key=${B2_SECRET_KEY}
b2.bucket=${B2_BUCKET}
b2.region=${B2_REGION}

# Spring Boot multipart
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

spring.servlet.multipart.file-size-threshold=0
spring.servlet.multipart.location=/tmp/uploads

server.tomcat.max-swallow-size=-1
